/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-10-19
 *
 */

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:isar_community/isar.dart';

import '../../../../models/isar/models/blockchain_data/transaction.dart';
import '../../../../models/isar/models/blockchain_data/v2/transaction_v2.dart';
import '../../../../providers/db/main_db_provider.dart';
import '../../../../providers/global/wallets_provider.dart';
import '../../../../themes/stack_colors.dart';
import '../../../../utilities/constants.dart';
import '../../../../utilities/util.dart';
import '../../../../wallets/crypto_currency/crypto_currency.dart';
import '../../../../wallets/isar/models/wallet_info.dart';
import '../../../../wallets/wallet/wallet_mixin_interfaces/cash_fusion_interface.dart';
import '../../../../widgets/loading_indicator.dart';
import '../../../../widgets/paginated_list_view.dart';
import '../../sub_widgets/no_transactions_found.dart';
import '../../wallet_view.dart';
import 'fusion_tx_group_card.dart';
import 'transaction_v2_list_item.dart';

class TransactionsV2List extends ConsumerStatefulWidget {
  const TransactionsV2List({super.key, required this.walletId});

  final String walletId;

  @override
  ConsumerState<TransactionsV2List> createState() => _TransactionsV2ListState();
}

class _TransactionsV2ListState extends ConsumerState<TransactionsV2List> {
  bool _hasLoaded = false;
  List<TransactionV2> _transactions = [];
  // Cached, already-sorted+processed view of [_transactions]. Recomputed only
  // when the underlying data changes (initial load / db watch), never per
  // build — avoids re-querying + reprocessing the whole list on every rebuild
  // (e.g. when returning from a transaction details page).
  List<Object> _txns = [];

  late final StreamSubscription<List<TransactionV2>> _subscription;
  late final Query<TransactionV2> _query;
  late final CryptoCurrency coin;

  BorderRadius get _borderRadiusFirst {
    return BorderRadius.only(
      topLeft: Radius.circular(Constants.size.circularBorderRadius),
      topRight: Radius.circular(Constants.size.circularBorderRadius),
    );
  }

  BorderRadius get _borderRadiusLast {
    return BorderRadius.only(
      bottomLeft: Radius.circular(Constants.size.circularBorderRadius),
      bottomRight: Radius.circular(Constants.size.circularBorderRadius),
    );
  }

  List<Object> _processData(List<TransactionV2> transactions) {
    if (ref.read(pWallets).getWallet(widget.walletId) is! CashFusionInterface) {
      return transactions;
    }

    final List<Object> processed = [];

    List<TransactionV2> fusions = [];

    for (int i = 0; i < transactions.length; i++) {
      final tx = transactions[i];

      if (tx.subType == TransactionSubType.cashFusion) {
        if (fusions.isNotEmpty) {
          final prevTime = DateTime.fromMillisecondsSinceEpoch(
            fusions.last.timestamp * 1000,
          );
          final thisTime = DateTime.fromMillisecondsSinceEpoch(
            tx.timestamp * 1000,
          );

          if (prevTime.difference(thisTime).inMinutes > 30) {
            processed.add(FusionTxGroup(fusions));
            fusions = [tx];
            continue;
          }
        }

        fusions.add(tx);
      }

      if (i + 1 < transactions.length) {
        final nextTx = transactions[i + 1];
        if (nextTx.subType != TransactionSubType.cashFusion &&
            fusions.isNotEmpty) {
          processed.add(FusionTxGroup(fusions));
          fusions = [];
        }
      }

      if (tx.subType != TransactionSubType.cashFusion) {
        processed.add(tx);
      }
    }

    return processed;
  }

  /// Redesign: rows carry only their time; the date moves into section
  /// headers ("TODAY", "31 AUG") interleaved into the list as Strings.
  /// The list is already sorted newest-first, so one pass suffices.
  List<Object> _withDateHeaders(List<Object> items) {
    final out = <Object>[];
    String? last;
    for (final item in items) {
      final ts = item is TransactionV2
          ? item.timestamp
          : (item as FusionTxGroup).transactions.first.timestamp;
      final label = _dayLabel(ts);
      if (label != last) {
        out.add(label);
        last = label;
      }
      out.add(item);
    }
    return out;
  }

  String _dayLabel(int timestamp) {
    final d = DateTime.fromMillisecondsSinceEpoch(timestamp * 1000);
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final day = DateTime(d.year, d.month, d.day);
    if (day == today) return "TODAY";
    if (day == today.subtract(const Duration(days: 1))) return "YESTERDAY";
    final base = "${d.day} ${Constants.monthMapShort[d.month]}".toUpperCase();
    // The year only where it is not this year — "31 AUG" needs no 2026.
    return d.year == now.year ? base : "$base ${d.year}";
  }

  void _rebuildData() {
    _transactions.sort((a, b) {
      final compare = b.timestamp.compareTo(a.timestamp);
      if (compare == 0) {
        return b.id.compareTo(a.id);
      }
      return compare;
    });
    _txns = _withDateHeaders(_processData(_transactions));

    // A shortened list must say so. Showing the most recent few thousand of a
    // pool address's history as though it were everything would be a claim we
    // cannot support, so the count the sync recorded is surfaced here.
    final total =
        ref
                .read(pWallets)
                .getWallet(widget.walletId)
                .info
                .otherData[WalletInfoKeys.historyTruncatedTotal]
            as int?;
    if (total != null && total > _transactions.length) {
      _txns = [_TruncationNotice(total), ..._txns];
    }
  }

  @override
  void initState() {
    coin = ref.read(pWallets).getWallet(widget.walletId).info.coin;
    _query = ref
        .read(mainDBProvider)
        .isar
        .transactionV2s
        .buildQuery<TransactionV2>(
          whereClauses: [
            IndexWhereClause.equalTo(
              indexName: 'walletId',
              value: [widget.walletId],
            ),
          ],
          filter: ref
              .read(pWallets)
              .getWallet(widget.walletId)
              .transactionFilterOperation,
          sortBy: [const SortProperty(property: "timestamp", sort: Sort.desc)],
        );

    // Initial load once (synchronous), then rely on the db watch for updates.
    _transactions = _query.findAllSync();
    _rebuildData();
    _hasLoaded = true;

    _subscription = _query.watch().listen((event) {
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (mounted) {
          setState(() {
            _transactions = event;
            _rebuildData();
          });
        }
      });
    });

    super.initState();
  }

  @override
  void dispose() {
    _subscription.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!_hasLoaded) {
      return const Column(
        children: [
          Spacer(),
          Center(child: LoadingIndicator(height: 50, width: 50)),
          Spacer(flex: 4),
        ],
      );
    }
    if (_txns.isEmpty) {
      return const NoTransActionsFound();
    }
    return RefreshIndicator(
            onRefresh: () async {
              await ref.read(pWallets).getWallet(widget.walletId).refresh();
            },
            child: Util.isDesktop
                ? PaginatedListView(
                    // Desktop keeps its paginated flat list; headers are a
                    // mobile treatment and pagination would orphan them.
                    items: _txns.where((e) => e is! String).toList(),
                    itemBuilder: (context, tx, position) {
                      final radius = switch (position) {
                        PageItemPosition.first => _borderRadiusFirst,
                        PageItemPosition.last => _borderRadiusLast,
                        PageItemPosition.solo => BorderRadius.circular(
                          Constants.size.circularBorderRadius,
                        ),
                        PageItemPosition.somewhere => null,
                      };

                      return TxListItem(tx: tx, coin: coin, radius: radius);
                    },
                  )
                : ListView.builder(
                    padding: const EdgeInsets.only(bottom: 92),
                    itemCount: _txns.length,
                    itemBuilder: (context, index) {
                      BorderRadius? radius;
                      bool shouldWrap = false;
                      if (_txns.length == 1) {
                        radius = BorderRadius.circular(
                          Constants.size.circularBorderRadius,
                        );
                      } else if (index == _txns.length - 1) {
                        radius = _borderRadiusLast;
                        shouldWrap = true;
                      } else if (index == 0) {
                        radius = _borderRadiusFirst;
                      }
                      final tx = _txns[index];
                      if (tx is String) {
                        return _DateHeader(label: tx);
                      }
                      if (tx is _TruncationNotice) {
                        return _TruncationBanner(total: tx.total);
                      }
                      if (shouldWrap) {
                        return Column(
                          children: [
                            TxListItem(tx: tx, coin: coin, radius: radius),
                            const SizedBox(
                              height: WalletView.navBarHeight + 14,
                            ),
                          ],
                        );
                      } else {
                        return TxListItem(tx: tx, coin: coin, radius: radius);
                      }
                    },
                  ),
          );
  }
}

/// A day-section header row: "TODAY", "YESTERDAY", "31 AUG", "5 JAN 2025".
class _DateHeader extends StatelessWidget {
  const _DateHeader({required this.label});

  final String label;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(left: 4, top: 10, bottom: 6),
      child: Align(
        alignment: Alignment.centerLeft,
        child: Text(
          label,
          style: TextStyle(
            fontSize: 11,
            fontWeight: FontWeight.w600,
            letterSpacing: 1.0,
            color: Theme.of(context).extension<StackColors>()!.textSubtitle1,
          ),
        ),
      ),
    );
  }
}

/// Marker for the list: this address has more history than was synced.
class _TruncationNotice {
  const _TruncationNotice(this.total);
  final int total;
}

/// Says plainly that the list below is partial, and that the balance is not.
///
/// Exchange and pool addresses run to tens of thousands of transactions, which
/// cannot be walked in one sync. The balance stays exact because it is derived
/// from unspent outputs rather than from this list, and saying both halves out
/// loud is the point: a short list with no explanation reads as a wrong list.
class _TruncationBanner extends StatelessWidget {
  const _TruncationBanner({required this.total});

  final int total;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;
    return Container(
      margin: const EdgeInsets.only(top: 8, bottom: 4),
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
      decoration: BoxDecoration(
        color: colors.popupBG,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: colors.textSubtitle1.withOpacity(0.15),
          width: 1,
        ),
      ),
      child: Row(
        children: [
          Icon(Icons.info_outline, size: 18, color: colors.textSubtitle1),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              "This address has about $total transactions, too many to load "
              "in full. Showing the most recent. The balance above is exact.",
              style: TextStyle(fontSize: 12, color: colors.textSubtitle1),
            ),
          ),
        ],
      ),
    );
  }
}
