/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/cupertino.dart' show CupertinoIcons;
import 'package:flutter/material.dart';
import '../../themes/stack_colors.dart';
import '../../utilities/assets.dart';
import '../../utilities/ios_icon.dart';

class PencilIcon extends StatelessWidget {
  const PencilIcon({
    super.key,
    this.width = 18,
    this.height = 18,
    this.color,
  });

  final double width;
  final double height;
  final Color? color;

  @override
  Widget build(BuildContext context) {
    return adaptiveIcon(
      Assets.svg.pencil,
      CupertinoIcons.pencil,
      size: width,
      color: color ?? Theme.of(context).extension<StackColors>()!.textDark3,
    );
  }
}
