import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
// NOTE: package name = the fork's pubspec `name` (configure_bitfinite.sh sets
// it to `bitfinite`). If yours differs, adjust this import.
import 'package:bitfinite/utilities/bfx_cashaddr.dart';

Uint8List _hex(String h) {
  final out = Uint8List(h.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(h.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String _toHex(List<int> b) =>
    b.map((e) => e.toRadixString(16).padLeft(2, "0")).join();

/// (hash160 hex, type, expected "bfx:" address)
/// All generated by the reference algorithm and cross-checked against the live
/// founder address (row 1) which was produced by BitFinite core.
const _vectors = <(String, int, String)>[
  ("fa220c48a3c616e37850e74052910296462ed1b2", 0,
      "bfx:frazyrzg50rpdcmc2rn5f553f2tyvtk3kgjszd0v33"),
  ("0000000000000000000000000000000000000000", 0,
      "bfx:ffffffffffffffffffffffffffffffffff0au86eg7"),
  ("ffffffffffffffffffffffffffffffffffffffff", 0,
      "bfx:frllllllllllllllllllllllllllllllluj24s4exd"),
  ("76a04053bda0a88bda5177b86a15c3b29f559873", 1,
      "bfx:ppm2fsznhks23z7629mms6s4cweq74vcwv4pukfxx0"),
];

void main() {
  group("BfxCashAddr", () {
    test("charset is BCH standard with q<->f swapped", () {
      const std = "qpzry9x8gf2tvdw0s3jn54khce6mua7l";
      expect(BfxCashAddr.charset.length, 32);
      // only indices 0 and 9 differ
      final diffs = <int>[];
      for (var i = 0; i < 32; i++) {
        if (BfxCashAddr.charset[i] != std[i]) diffs.add(i);
      }
      expect(diffs, [0, 9]);
      expect(BfxCashAddr.charset[0], "f");
      expect(BfxCashAddr.charset[9], "q");
    });

    test("encode matches known vectors", () {
      for (final (hashHex, type, addr) in _vectors) {
        final got = BfxCashAddr.encode(hash160: _hex(hashHex), type: type);
        expect(got, addr, reason: "encode $hashHex/$type");
      }
    });

    test("decode matches known vectors", () {
      for (final (hashHex, type, addr) in _vectors) {
        final d = BfxCashAddr.decode(addr);
        expect(d.type, type, reason: "type of $addr");
        expect(_toHex(d.hash160), hashHex, reason: "hash160 of $addr");
      }
    });

    test("round-trips", () {
      for (final (hashHex, type, _) in _vectors) {
        final addr = BfxCashAddr.encode(hash160: _hex(hashHex), type: type);
        final d = BfxCashAddr.decode(addr);
        expect(_toHex(d.hash160), hashHex);
        expect(d.type, type);
      }
    });

    test("P2PKH addresses start with 'bfx:f', P2SH with 'bfx:p'", () {
      final p2pkh = BfxCashAddr.encode(
        hash160: _hex("fa220c48a3c616e37850e74052910296462ed1b2"),
        type: BfxCashAddr.typeP2PKH,
      );
      final p2sh = BfxCashAddr.encode(
        hash160: _hex("76a04053bda0a88bda5177b86a15c3b29f559873"),
        type: BfxCashAddr.typeP2SH,
      );
      expect(p2pkh.startsWith("bfx:f"), true);
      expect(p2sh.startsWith("bfx:p"), true);
    });

    test("isValid true for good, false for corrupted checksum", () {
      const good = "bfx:frazyrzg50rpdcmc2rn5f553f2tyvtk3kgjszd0v33";
      expect(BfxCashAddr.isValid(good), true);

      // flip one payload char -> checksum must fail
      final bad = good.replaceRange(good.length - 1, good.length, "4");
      expect(BfxCashAddr.isValid(bad), false);
    });

    test("rejects a standard-charset (BCH-alphabet) address", () {
      // Same body but under the standard alphabet a BFX P2PKH would look like
      // 'bfx:q...'. Its checksum was computed for the BCH alphabet, so it must
      // fail under BFX. (Sanity: BFX and BCH addresses are mutually invalid.)
      const bchStyle = "bfx:qrazyrzg50rpdcmc2rn5f553f2tyvtk3kgjszd0v33";
      expect(BfxCashAddr.isValid(bchStyle), false);
    });

    test("decode is case-insensitive on the payload", () {
      const good = "bfx:frazyrzg50rpdcmc2rn5f553f2tyvtk3kgjszd0v33";
      expect(BfxCashAddr.isValid(good.toUpperCase()), true);
    });
  });
}
