/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/cupertino.dart' show CupertinoIcons;
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../themes/stack_colors.dart';
import '../../../../utilities/ios_icon.dart';
import '../../../../utilities/assets.dart';

class CoinControlNavIcon extends StatelessWidget {
  const CoinControlNavIcon({super.key});

  @override
  Widget build(BuildContext context) {
    return adaptiveIcon(
      Assets.svg.coinControl.gamePad,
      CupertinoIcons.square_grid_2x2,
      size: 20,
      color: Theme.of(context).extension<StackColors>()!.bottomNavIconIcon,
    );
  }
}
