/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../themes/stack_colors.dart';
import '../../../../utilities/hero_ink.dart';
import '../../../../utilities/assets.dart';

class ReceiveNavIcon extends StatelessWidget {
  const ReceiveNavIcon({super.key, this.onFilled = false, this.fill});

  /// True when this icon sits on the filled primary pill (the Receive page,
  /// where Receive is the active action). Green on the primary fill is muddy
  /// and low contrast, so the filled state uses the theme's button ink like
  /// the Send icon does.
  final bool onFilled;

  /// The colour of the pill this icon is painted on, when it is on one.
  ///
  /// The ink check below is only meaningful against the colour actually behind
  /// the icon. The dock paints its pill in the wallet's coin colour, which is
  /// not the theme's primary, so measuring against the primary answered a
  /// question nobody asked: on Pepecoin the arrow came out white on the wallet
  /// view and dark on the send screen, from the same widget.
  final Color? fill;

  @override
  Widget build(BuildContext context) {
    // Receive reads as incoming: green, matching the received transaction rows.
    // accentColorGreen is per-theme (Forest #00A591, OLED Black #4CC0A0), so
    // this already follows the theme; only the filled state needed fixing.
    final colors = Theme.of(context).extension<StackColors>()!;
    final tint = onFilled
        ? readableInk(colors.buttonTextPrimary, fill ?? colors.buttonBackPrimary)
        : colors.accentColorGreen;
    return Container(
      decoration: BoxDecoration(
        color: tint.withOpacity(onFilled ? 0.18 : 0.15),
        borderRadius: BorderRadius.circular(
          24,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SvgPicture.asset(
          Assets.svg.arrowDownLeft,
          width: 14,
          height: 14,
          color: tint,
        ),
      ),
    );
  }
}
