/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../themes/stack_colors.dart';
import '../../../../utilities/assets.dart';

class SendNavIcon extends StatelessWidget {
  const SendNavIcon({super.key});

  @override
  Widget build(BuildContext context) {
    // Send reads as outgoing: the accent blue, matching the primary actions.
    final blue = Theme.of(context).extension<StackColors>()!.accentColorBlue;
    return Container(
      decoration: BoxDecoration(
        color: blue.withOpacity(0.15),
        borderRadius: BorderRadius.circular(
          24,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SvgPicture.asset(
          Assets.svg.arrowUpRight,
          width: 14,
          height: 14,
          color: blue,
        ),
      ),
    );
  }
}
