/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../themes/stack_colors.dart';
import '../../../../utilities/hero_ink.dart';
import '../../../../utilities/assets.dart';

class SendNavIcon extends StatelessWidget {
  const SendNavIcon({super.key, this.onFilled = false, this.fill});

  /// True when this icon sits on the filled primary pill.
  ///
  /// Without it the icon vanished: the disc, the arrow and the pill are all the
  /// theme's primary colour — primary on primary. The Send action appeared to
  /// have no icon at all, which also made Receive (a bright green disc) read as
  /// the active one.
  final bool onFilled;

  /// The colour of the pill this icon is painted on, when it is on one.
  ///
  /// The ink check below is only meaningful against the colour actually behind
  /// the icon. The dock paints its pill in the wallet's coin colour, which is
  /// not the theme's primary, so measuring against the primary answered a
  /// question nobody asked: on Pepecoin the arrow came out white on the wallet
  /// view and dark on the send screen, from the same widget.
  final Color? fill;

  @override
  Widget build(BuildContext context) {
    // Send reads as outgoing in the theme's primary colour, matching the
    // primary actions. On the filled pill the roles invert to that theme's own
    // button ink — which is black, not white, in OLED Black.
    final colors = Theme.of(context).extension<StackColors>()!;
    // On the pill the icon must survive the same check as the label beside it,
    // or the two disagree — Orange's declared white is 3.00:1 on its own fill.
    final tint = onFilled
        ? readableInk(colors.buttonTextPrimary, fill ?? colors.buttonBackPrimary)
        : colors.buttonBackPrimary;
    return Container(
      decoration: BoxDecoration(
        color: tint.withOpacity(onFilled ? 0.18 : 0.15),
        borderRadius: BorderRadius.circular(
          24,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SvgPicture.asset(
          Assets.svg.arrowUpRight,
          width: 14,
          height: 14,
          color: tint,
        ),
      ),
    );
  }
}
