/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../themes/stack_colors.dart';
import '../../../../utilities/assets.dart';

class SendNavIcon extends StatelessWidget {
  const SendNavIcon({super.key, this.onFilled = false});

  /// True when this icon sits on the filled brand-blue pill.
  ///
  /// Without it the icon vanished: both the disc and the arrow are painted in
  /// accentColorBlue, and the filled pill is now that same blue — blue on blue.
  /// The Send action appeared to have no icon at all, which also made Receive
  /// (a bright green disc) read as the active one.
  final bool onFilled;

  @override
  Widget build(BuildContext context) {
    // Send reads as outgoing: the accent blue, matching the primary actions.
    // On the filled pill the roles invert — white on blue, per the design
    // (disc rgba(255,255,255,0.18), arrow #FFFFFF).
    final blue = Theme.of(context).extension<StackColors>()!.accentColorBlue;
    final tint = onFilled ? Colors.white : blue;
    return Container(
      decoration: BoxDecoration(
        color: tint.withOpacity(onFilled ? 0.18 : 0.15),
        borderRadius: BorderRadius.circular(
          24,
        ),
      ),
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SvgPicture.asset(
          Assets.svg.arrowUpRight,
          width: 14,
          height: 14,
          color: tint,
        ),
      ),
    );
  }
}
