/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io' show Platform;
import 'dart:ui' show ColorFilter, ImageFilter;

import 'package:flutter/cupertino.dart' show CupertinoIcons;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';
import '../../themes/stack_colors.dart';
import '../../utilities/assets.dart';
import '../../utilities/constants.dart';
import '../../utilities/text_styles.dart';
import 'components/wallet_navigation_bar_item.dart';

final walletNavBarMore = StateProvider.autoDispose((ref) => false);

/// Native iOS (SF Symbols via CupertinoIcons) glyphs for the floating dock,
/// keyed by action label. Returns null for labels without a mapping (caller
/// falls back to the app's classic icon).
const Map<String, IconData> _iosNavIcons = <String, IconData>{
  "Receive": CupertinoIcons.arrow_down_left,
  "Send": CupertinoIcons.arrow_up_right,
  "More": CupertinoIcons.ellipsis,
};

/// Gap between actions in the floating dock.
const double _dockGap = 24;

/// A colour matrix that scales saturation by [s] about luminance, matching the
/// saturation lift iOS applies in its vibrancy materials.
List<double> _saturate(double s) {
  const lumR = 0.2126, lumG = 0.7152, lumB = 0.0722;
  final r = (1 - s) * lumR, g = (1 - s) * lumG, b = (1 - s) * lumB;
  return <double>[
    r + s, g, b, 0, 0, //
    r, g + s, b, 0, 0, //
    r, g, b + s, 0, 0, //
    0, 0, 0, 1, 0, //
  ];
}

Widget? iosNavIcon(String? label, Color color) {
  // SF Symbols are Apple's design language - on Android the dock keeps the
  // app's own icon set, so only map these on iOS.
  if (!Platform.isIOS) return null;
  final icon = _iosNavIcons[label];
  if (icon == null) return null;
  return Icon(icon, size: 24, color: color);
}

/// Wallet actions as first-class in-flow buttons (Receive / Send / …) with a
/// "More" button that opens the remaining actions in a bottom sheet.
/// Replaces the old floating bottom dock.
class WalletNavigationBar extends ConsumerWidget {
  const WalletNavigationBar({
    super.key,
    required this.items,
    required this.moreItems,
    this.floating = false,
  });

  final List<WalletNavigationBarItemData> items;
  final List<WalletNavigationBarItemData> moreItems;

  /// When true, renders as a frosted, rounded "pill" dock (iOS style) that
  /// hugs its content, instead of the full-width in-flow button row.
  final bool floating;

  void _showMoreSheet(BuildContext context) {
    showModalBottomSheet<void>(
      context: context,
      backgroundColor: Theme.of(context).extension<StackColors>()!.popupBG,
      useSafeArea: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (sheetContext) => SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 8),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              for (final item in moreItems)
                ListTile(
                  leading: SizedBox(width: 24, height: 24, child: item.icon),
                  title: Text(
                    item.label ?? "",
                    style: STextStyles.titleBold12(sheetContext),
                  ),
                  onTap: () {
                    Navigator.of(sheetContext).pop();
                    item.onTap?.call();
                  },
                ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final colors = Theme.of(context).extension<StackColors>()!;
    final hasMore = moreItems.isNotEmpty;

    final buttons = <Widget>[
      for (int i = 0; i < items.length; i++)
        _ActionButton(
          data: items[i],
          floating: floating,
          highlighted: floating && i == 0,
        ),
      if (hasMore)
        _ActionButton(
          floating: floating,
          data: WalletNavigationBarItemData(
            label: "More",
            icon: SvgPicture.asset(
              Assets.svg.bars,
              width: 20,
              height: 20,
              color: colors.bottomNavIconIcon,
            ),
            onTap: () => _showMoreSheet(context),
          ),
        ),
    ];

    if (floating) {
      // Frosted glass is an iOS idiom, and BackdropFilter is measurably more
      // expensive on low-end Android GPUs. Android gets the same dock shape
      // over a solid themed surface instead.
      final bool glass = Platform.isIOS;

      final Widget surface = Container(
        key: const Key("walletDockSurface"),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(999),
          // Glass: only a whisper of fill over the blur, so content behind
          // stays legible. NB: a `color:` alongside would be silently ignored -
          // gradient wins in BoxDecoration.
          gradient: glass
              ? LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Colors.white.withOpacity(0.22),
                    Colors.white.withOpacity(0.06),
                  ],
                )
              : null,
          color: glass ? null : colors.popupBG,
          // A hairline so the solid pill reads as a distinct surface on every
          // theme - on a light theme a white pill on a light background was
          // otherwise invisible. Derived from the dock's own text colour, so it
          // contrasts against the surface in both light and dark themes.
          border: Border.all(
            color: glass
                ? Colors.white.withOpacity(0.30)
                : colors.bottomNavText.withOpacity(0.22),
            width: 1,
          ),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(glass ? 0.18 : 0.22),
              blurRadius: 24,
              offset: const Offset(0, 8),
            ),
          ],
        ),
        padding: const EdgeInsets.symmetric(vertical: 6, horizontal: 6),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            for (int i = 0; i < buttons.length; i++) ...[
              if (i > 0) const SizedBox(width: _dockGap),
              buttons[i],
            ],
          ],
        ),
      );

      return SafeArea(
        top: false,
        // Lift the pill off the bottom edge so it reads as floating rather than
        // stuck to the navigation area.
        minimum: const EdgeInsets.only(bottom: 10),
        // The pill hugs its actions rather than spanning a fixed width, so the
        // spacing between icons stays consistent no matter how many there are
        // (a fixed width left big dead gaps with only three).
        child: Center(
          child: ClipRRect(
            borderRadius: BorderRadius.circular(999),
            child: glass
                ? BackdropFilter(
                    // iOS vibrancy is a blur *plus* a saturation boost -
                    // without the boost the backdrop reads as flat grey haze
                    // instead of glass.
                    filter: ImageFilter.compose(
                      outer: ImageFilter.blur(sigmaX: 24, sigmaY: 24),
                      inner: ColorFilter.matrix(_saturate(1.7)),
                    ),
                    child: surface,
                  )
                : surface,
          ),
        ),
      );
    }

    return Row(
      children: [
        for (int i = 0; i < buttons.length; i++) ...[
          if (i > 0) const SizedBox(width: 9),
          Expanded(child: buttons[i]),
        ],
      ],
    );
  }
}

class _ActionButton extends StatelessWidget {
  const _ActionButton({
    required this.data,
    this.floating = false,
    this.highlighted = false,
  });

  final WalletNavigationBarItemData data;
  final bool floating;
  final bool highlighted;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;

    // iOS floating dock: icon-only, no per-icon circle. The active/primary
    // item gets a lighter circle behind it; the rest are plain icons that
    // chip on press.
    if (floating) {
      return Material(
        // On glass (iOS) the SF glyph has no circle of its own, so the active
        // item gets a translucent white wash behind it. On Android the icons
        // (ReceiveNavIcon/SendNavIcon) already carry their own circle - like the
        // transaction list - so a highlight circle here would double it up.
        // Keep them single: no extra circle on Android.
        color: highlighted && Platform.isIOS
            ? Colors.white.withOpacity(0.35)
            : Colors.transparent,
        // Circular highlight (not a rounded rect) behind the active action.
        shape: const CircleBorder(),
        clipBehavior: Clip.antiAlias,
        child: InkWell(
          customBorder: const CircleBorder(),
          highlightColor: Colors.white.withOpacity(0.25),
          onTap: data.onTap,
          child: SizedBox(
            width: 48,
            height: 48,
            child: Center(
              child:
                  iosNavIcon(data.label, colors.bottomNavIconIcon) ??
                  SizedBox(width: 22, height: 22, child: data.icon),
            ),
          ),
        ),
      );
    }

    return Material(
      color: colors.popupBG,
      borderRadius: BorderRadius.circular(Constants.size.circularBorderRadius),
      child: InkWell(
        borderRadius: BorderRadius.circular(
          Constants.size.circularBorderRadius,
        ),
        onTap: data.onTap,
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 4),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                width: 30,
                height: 30,
                decoration: BoxDecoration(
                  color: colors.accentColorBlue.withOpacity(0.15),
                  borderRadius: BorderRadius.circular(999),
                ),
                child: Center(
                  child: SizedBox(width: 18, height: 18, child: data.icon),
                ),
              ),
              const SizedBox(height: 5),
              data.overrideText ??
                  Text(
                    data.label ?? "",
                    style: STextStyles.buttonSmall(context).copyWith(
                      fontSize: 11.5,
                      fontWeight: FontWeight.w500,
                      color: colors.bottomNavText,
                    ),
                  ),
            ],
          ),
        ),
      ),
    );
  }
}
