/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:ui' show ImageFilter;

import 'package:flutter/cupertino.dart' show CupertinoIcons;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';
import '../../themes/stack_colors.dart';
import '../../utilities/assets.dart';
import '../../utilities/constants.dart';
import '../../utilities/text_styles.dart';
import 'components/wallet_navigation_bar_item.dart';

final walletNavBarMore = StateProvider.autoDispose((ref) => false);

/// Native iOS (SF Symbols via CupertinoIcons) glyphs for the floating dock,
/// keyed by action label. Returns null for labels without a mapping (caller
/// falls back to the app's classic icon).
const Map<String, IconData> _iosNavIcons = <String, IconData>{
  "Receive": CupertinoIcons.arrow_down_left,
  "Send": CupertinoIcons.arrow_up_right,
  "More": CupertinoIcons.ellipsis,
};

Widget? iosNavIcon(String? label, Color color) {
  final icon = _iosNavIcons[label];
  if (icon == null) return null;
  return Icon(icon, size: 24, color: color);
}

/// Wallet actions as first-class in-flow buttons (Receive / Send / …) with a
/// "More" button that opens the remaining actions in a bottom sheet.
/// Replaces the old floating bottom dock.
class WalletNavigationBar extends ConsumerWidget {
  const WalletNavigationBar({
    super.key,
    required this.items,
    required this.moreItems,
    this.floating = false,
  });

  final List<WalletNavigationBarItemData> items;
  final List<WalletNavigationBarItemData> moreItems;

  /// When true, renders as a frosted, rounded "pill" dock (iOS style) that
  /// hugs its content, instead of the full-width in-flow button row.
  final bool floating;

  void _showMoreSheet(BuildContext context) {
    showModalBottomSheet<void>(
      context: context,
      backgroundColor: Theme.of(context).extension<StackColors>()!.popupBG,
      useSafeArea: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (sheetContext) => SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 8),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              for (final item in moreItems)
                ListTile(
                  leading: SizedBox(width: 24, height: 24, child: item.icon),
                  title: Text(
                    item.label ?? "",
                    style: STextStyles.titleBold12(sheetContext),
                  ),
                  onTap: () {
                    Navigator.of(sheetContext).pop();
                    item.onTap?.call();
                  },
                ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final colors = Theme.of(context).extension<StackColors>()!;
    final hasMore = moreItems.isNotEmpty;

    final buttons = <Widget>[
      for (int i = 0; i < items.length; i++)
        _ActionButton(
          data: items[i],
          floating: floating,
          highlighted: floating && i == 0,
        ),
      if (hasMore)
        _ActionButton(
          floating: floating,
          data: WalletNavigationBarItemData(
            label: "More",
            icon: SvgPicture.asset(
              Assets.svg.bars,
              width: 20,
              height: 20,
              color: colors.bottomNavIconIcon,
            ),
            onTap: () => _showMoreSheet(context),
          ),
        ),
    ];

    if (floating) {
      return SafeArea(
        top: false,
        minimum: const EdgeInsets.only(bottom: 4),
        child: Align(
          alignment: Alignment.center,
          heightFactor: 1.0,
          child: ClipRRect(
            borderRadius: BorderRadius.circular(999),
            child: BackdropFilter(
              filter: ImageFilter.blur(sigmaX: 30, sigmaY: 30),
              child: Container(
                decoration: BoxDecoration(
                  // Frosted-glass: low-opacity fill over a strong blur so the
                  // content scrolls through, with a bright hairline edge.
                  color: colors.bottomNavBack.withOpacity(0.55),
                  borderRadius: BorderRadius.circular(999),
                  border: Border.all(
                    color: Colors.white.withOpacity(0.14),
                  ),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.20),
                      blurRadius: 24,
                      offset: const Offset(0, 8),
                    ),
                  ],
                ),
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    for (int i = 0; i < buttons.length; i++) ...[
                      if (i > 0) const SizedBox(width: 6),
                      buttons[i],
                    ],
                  ],
                ),
              ),
            ),
          ),
        ),
      );
    }

    return Row(
      children: [
        for (int i = 0; i < buttons.length; i++) ...[
          if (i > 0) const SizedBox(width: 9),
          Expanded(child: buttons[i]),
        ],
      ],
    );
  }
}

class _ActionButton extends StatelessWidget {
  const _ActionButton({
    required this.data,
    this.floating = false,
    this.highlighted = false,
  });

  final WalletNavigationBarItemData data;
  final bool floating;
  final bool highlighted;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;

    // iOS floating dock: icon-only, no per-icon circle. The active/primary
    // item gets a lighter rounded "chip" behind it (adopted from a modern
    // pill-nav pattern); the rest are plain icons that chip on press.
    if (floating) {
      return Material(
        color: highlighted ? colors.bottomNavIconBack : Colors.transparent,
        borderRadius: BorderRadius.circular(18),
        child: InkWell(
          borderRadius: BorderRadius.circular(18),
          highlightColor: colors.bottomNavIconBack,
          onTap: data.onTap,
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 11, horizontal: 22),
            child: SizedBox(
              width: 24,
              height: 24,
              child: Center(
                child:
                    iosNavIcon(data.label, colors.bottomNavIconIcon) ??
                    SizedBox(width: 22, height: 22, child: data.icon),
              ),
            ),
          ),
        ),
      );
    }

    return Material(
      color: colors.popupBG,
      borderRadius: BorderRadius.circular(Constants.size.circularBorderRadius),
      child: InkWell(
        borderRadius: BorderRadius.circular(
          Constants.size.circularBorderRadius,
        ),
        onTap: data.onTap,
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 4),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                width: 30,
                height: 30,
                decoration: BoxDecoration(
                  color: colors.accentColorBlue.withOpacity(0.15),
                  borderRadius: BorderRadius.circular(999),
                ),
                child: Center(
                  child: SizedBox(width: 18, height: 18, child: data.icon),
                ),
              ),
              const SizedBox(height: 5),
              data.overrideText ??
                  Text(
                    data.label ?? "",
                    style: STextStyles.buttonSmall(context).copyWith(
                      fontSize: 11.5,
                      fontWeight: FontWeight.w500,
                      color: colors.bottomNavText,
                    ),
                  ),
            ],
          ),
        ),
      ),
    );
  }
}
