/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';
import '../../themes/stack_colors.dart';
import '../../utilities/assets.dart';
import '../../utilities/constants.dart';
import '../../utilities/text_styles.dart';
import 'components/wallet_navigation_bar_item.dart';

final walletNavBarMore = StateProvider.autoDispose((ref) => false);

/// Wallet actions as first-class in-flow buttons (Receive / Send / …) with a
/// "More" button that opens the remaining actions in a bottom sheet.
/// Replaces the old floating bottom dock.
class WalletNavigationBar extends ConsumerWidget {
  const WalletNavigationBar({
    super.key,
    required this.items,
    required this.moreItems,
  });

  final List<WalletNavigationBarItemData> items;
  final List<WalletNavigationBarItemData> moreItems;

  void _showMoreSheet(BuildContext context) {
    showModalBottomSheet<void>(
      context: context,
      backgroundColor: Theme.of(context).extension<StackColors>()!.popupBG,
      useSafeArea: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (sheetContext) => SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 8),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              for (final item in moreItems)
                ListTile(
                  leading: SizedBox(width: 24, height: 24, child: item.icon),
                  title: Text(
                    item.label ?? "",
                    style: STextStyles.titleBold12(sheetContext),
                  ),
                  onTap: () {
                    Navigator.of(sheetContext).pop();
                    item.onTap?.call();
                  },
                ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final colors = Theme.of(context).extension<StackColors>()!;
    final hasMore = moreItems.isNotEmpty;

    final buttons = <Widget>[
      for (final item in items) _ActionButton(data: item),
      if (hasMore)
        _ActionButton(
          data: WalletNavigationBarItemData(
            label: "More",
            icon: SvgPicture.asset(
              Assets.svg.bars,
              width: 20,
              height: 20,
              color: colors.bottomNavIconIcon,
            ),
            onTap: () => _showMoreSheet(context),
          ),
        ),
    ];

    return Row(
      children: [
        for (int i = 0; i < buttons.length; i++) ...[
          if (i > 0) const SizedBox(width: 9),
          Expanded(child: buttons[i]),
        ],
      ],
    );
  }
}

class _ActionButton extends StatelessWidget {
  const _ActionButton({required this.data});

  final WalletNavigationBarItemData data;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;

    return Material(
      color: colors.popupBG,
      borderRadius: BorderRadius.circular(Constants.size.circularBorderRadius),
      child: InkWell(
        borderRadius: BorderRadius.circular(
          Constants.size.circularBorderRadius,
        ),
        onTap: data.onTap,
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 4),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                width: 30,
                height: 30,
                decoration: BoxDecoration(
                  color: colors.accentColorBlue.withOpacity(0.15),
                  borderRadius: BorderRadius.circular(999),
                ),
                child: Center(
                  child: SizedBox(width: 18, height: 18, child: data.icon),
                ),
              ),
              const SizedBox(height: 5),
              data.overrideText ??
                  Text(
                    data.label ?? "",
                    style: STextStyles.buttonSmall(context).copyWith(
                      fontSize: 11.5,
                      fontWeight: FontWeight.w600,
                      color: colors.bottomNavText,
                    ),
                  ),
            ],
          ),
        ),
      ),
    );
  }
}
