/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';

import 'package:decimal/decimal.dart';
import 'package:flutter/foundation.dart';
import 'package:isar_community/isar.dart';

import '../db/isar/main_db.dart';
import '../models/isar/models/isar_models.dart';
import '../networking/http.dart';
import '../wallets/crypto_currency/crypto_currency.dart';
import 'price.dart';

class PriceService extends ChangeNotifier {
  late final String baseTicker;
  Future<Set<String>> get tokenContractAddressesToCheck async =>
      (await MainDB.instance.getEthContracts().addressProperty().findAll())
          .toSet();
  Future<Set<String>> get solTokenContractAddressesToCheck async =>
      (await MainDB.instance.getSolContracts().addressProperty().findAll())
          .toSet();
  final Duration updateInterval = const Duration(seconds: 60);

  Timer? _timer;
  final Map<CryptoCurrency, ({Decimal value, double change24h})> _cachedPrices =
      {};

  final Map<String, ({Decimal value, double change24h})> _cachedTokenPrices =
      {};

  final _priceAPI = PriceAPI(HTTP());

  /// A price of zero means "this coin is not listed on the price API", not
  /// "this coin is worth nothing". The upstream cache stores that as a real
  /// record, so every `price != null` check in the UI passed and rendered a
  /// fabricated "+0.00 USD" on every amount. BFX is unlisted, so that was the
  /// whole app.
  ///
  /// Normalised here rather than at the ~37 call sites: the callers already
  /// treat null as "no price and show nothing", which is exactly right.
  ({Decimal value, double change24h})? _orNullIfUnpriced(
    ({Decimal value, double change24h})? cached,
  ) => (cached == null || cached.value <= Decimal.zero) ? null : cached;

  ({Decimal value, double change24h})? getPrice(CryptoCurrency coin) =>
      _orNullIfUnpriced(_cachedPrices[coin]);

  ({Decimal value, double change24h})? getTokenPrice(String contractAddress) =>
      _orNullIfUnpriced(_cachedTokenPrices[contractAddress.toLowerCase()]);

  final Map<CryptoCurrency, List<double>> _cachedSparklines = {};

  /// 7-day hourly price series, or null when the coin has no market.
  ///
  /// Gated on getPrice for the same reason that exists: an unlisted coin caches
  /// a zero price, and a chart drawn from that would be a flat line at zero —
  /// a made-up claim rather than an absence. Callers render nothing on null.
  List<double>? getSparkline(CryptoCurrency coin) {
    if (getPrice(coin) == null) return null;
    final series = _cachedSparklines[coin];
    return (series != null && series.length > 1) ? series : null;
  }

  /// Price series for the hero chart's range selector. 7 days comes from the
  /// sparkline the price poll already carries (no extra request); 1 and 30
  /// days are fetched lazily and cached by PriceAPI. Same unlisted-coin gate
  /// as [getSparkline]: no market, no chart, never a flat line at zero.
  Future<List<double>?> getRangeSeries(CryptoCurrency coin, int days) async {
    if (getPrice(coin) == null) return null;
    if (days == 7) return getSparkline(coin);
    return await _priceAPI.getMarketChart(
      coin: coin,
      days: days,
      baseCurrency: baseTicker,
    );
  }

  PriceService(this.baseTicker);

  Future<void> updatePrice() async {
    final priceMap = await _priceAPI.getPricesAnd24hChange(
      baseCurrency: baseTicker,
    );

    _cachedSparklines
      ..clear()
      ..addAll(_priceAPI.sparklines);

    bool shouldNotify = false;
    for (final map in priceMap.entries) {
      if (_cachedPrices[map.key] != map.value) {
        _cachedPrices[map.key] = map.value;
        shouldNotify = true;
      }
    }

    final _tokenContractAddressesToCheck = await tokenContractAddressesToCheck;

    if (_tokenContractAddressesToCheck.isNotEmpty) {
      final tokenPriceMap = await _priceAPI.getPricesAnd24hChangeForEthTokens(
        contractAddresses: _tokenContractAddressesToCheck,
        baseCurrency: baseTicker,
      );

      for (final map in tokenPriceMap.entries) {
        if (_cachedTokenPrices[map.key] != map.value) {
          _cachedTokenPrices[map.key] = map.value;
          shouldNotify = true;
        }
      }
    }

    final _solTokenContractAddressesToCheck = await solTokenContractAddressesToCheck;

    if (_solTokenContractAddressesToCheck.isNotEmpty) {
      final solTokenPriceMap = await _priceAPI.getPricesAnd24hChangeForSolTokens(
        contractAddresses: _solTokenContractAddressesToCheck,
        baseCurrency: baseTicker,
      );

      for (final map in solTokenPriceMap.entries) {
        if (_cachedTokenPrices[map.key] != map.value) {
          _cachedTokenPrices[map.key] = map.value;
          shouldNotify = true;
        }
      }
    }

    if (shouldNotify) {
      notifyListeners();
    }
  }

  void cancel() {
    _timer?.cancel();
    _timer = null;
  }

  void start(bool rightAway) {
    if (rightAway) {
      updatePrice();
    }
    _timer?.cancel();
    _timer = Timer.periodic(updateInterval, (_) {
      updatePrice();
    });
  }

  @override
  void dispose() {
    cancel();
    super.dispose();
  }
}
