/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../themes/theme_providers.dart';

class LoadingIndicator extends ConsumerWidget {
  const LoadingIndicator({
    super.key,
    this.width,
    this.height,
  });

  final double? width;
  final double? height;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final assetPath = ref.watch(
      themeProvider.select((value) => value.assets.loadingGif),
    );

    return Container(
      color: Colors.transparent,
      child: Center(
        child: SizedBox(
          width: width,
          height: height,
          child: assetPath != null
              ? Image.file(
                  File(
                    assetPath,
                  ),
                )
              // BFX: no Stack lottie — plain brand-blue spinner.
              : const Center(
                  child: SizedBox(
                    width: 56,
                    height: 56,
                    child: CircularProgressIndicator(
                      strokeWidth: 4,
                      color: Color(0xFF0644F1),
                    ),
                  ),
                ),
        ),
      ),
    );
  }
}
