/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';
import 'package:tuple/tuple.dart';

import '../pages/coin_control/coin_control_view.dart';
import '../pages/receive_view/receive_view.dart';
import '../pages/send_view/send_view.dart';
import '../pages/wallet_view/transaction_views/tx_v2/all_transactions_v2_view.dart';
import '../providers/providers.dart';
import '../themes/stack_colors.dart';
import '../utilities/assets.dart';
import '../utilities/text_styles.dart';
import '../wallets/crypto_currency/crypto_currency.dart';
import '../wallets/wallet/wallet_mixin_interfaces/view_only_option_interface.dart';
import 'desktop/primary_button.dart';
import 'desktop/secondary_button.dart';
import 'wallet_navigation_bar/components/icons/coin_control_nav_icon.dart';

/// Which Receive/Send flow the page is currently showing.
enum TransferTab { receive, send }

/// The Receive/Send pages' bottom controls, in the SAME language as the
/// wallet home's action bar — the redesign replaced the floating icon dock
/// there, and a page that keeps the old dock reads as a different app.
///
/// Same grammar as the home bar: Send is the coin-filled primary, Receive the
/// secondary, extras (All transactions, Coin control) behind "···". The
/// button for the page you are on is a no-op — pressing "where you already
/// are" navigates nowhere — and the other switches flows via pushReplacement
/// so both still pop back to the wallet view. A view-only wallet gets no
/// Send here at all: the wallet home already explains the lock; inside the
/// transfer flow it would only repeat itself.
class ReceiveSendSwitchDock extends ConsumerWidget {
  const ReceiveSendSwitchDock({
    super.key,
    required this.current,
    required this.walletId,
    required this.coin,
  });

  final TransferTab current;
  final String walletId;
  final CryptoCurrency coin;

  void _showExtrasSheet(BuildContext context, WidgetRef ref) {
    final colors = Theme.of(context).extension<StackColors>()!;
    final coinControl = ref.read(prefsChangeNotifierProvider).enableCoinControl;

    showModalBottomSheet<void>(
      context: context,
      backgroundColor: colors.popupBG,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) => SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 12),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ListTile(
                leading: SvgPicture.asset(
                  Assets.svg.list,
                  width: 20,
                  height: 20,
                  color: colors.bottomNavIconIcon,
                ),
                title: Text(
                  "All transactions",
                  style: STextStyles.w500_14(context),
                ),
                onTap: () {
                  Navigator.of(context).pop();
                  Navigator.of(context).pushNamed(
                    AllTransactionsV2View.routeName,
                    arguments: walletId,
                  );
                },
              ),
              if (coinControl)
                ListTile(
                  leading: const CoinControlNavIcon(),
                  title: Text(
                    "Coin control",
                    style: STextStyles.w500_14(context),
                  ),
                  onTap: () {
                    Navigator.of(context).pop();
                    Navigator.of(context).pushNamed(
                      CoinControlView.routeName,
                      arguments: Tuple2(walletId, CoinControlViewType.manage),
                    );
                  },
                ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final colors = Theme.of(context).extension<StackColors>()!;

    // A view-only wallet has no keys, so it cannot sign anything. Same
    // predicate as the wallet home, same outcome, wherever the bar appears.
    final wallet = ref.watch(pWallets).getWallet(walletId);
    final viewOnly = wallet is ViewOnlyOptionInterface && wallet.isViewOnly;

    return SafeArea(
      top: false,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
        child: Row(
          children: [
            // The CURRENT tab wears the coin-filled primary — the bar is a
            // "you are here" indicator, so the active state must follow the
            // page (per the mockups: Send page shows a green-filled Send on
            // Pepecoin; Receive page shows a filled Receive). The first cut
            // kept Send always-primary, which read as Send being active
            // while you stood on Receive. The active button is a no-op
            // rather than disabled-grey: it is "here", not "unavailable".
            Expanded(
              child: current == TransferTab.receive
                  ? PrimaryButton(label: "Receive", onPressed: () {})
                  : SecondaryButton(
                      label: "Receive",
                      onPressed: () =>
                          Navigator.of(context).pushReplacementNamed(
                            ReceiveView.routeName,
                            arguments: walletId,
                          ),
                    ),
            ),
            if (!viewOnly) const SizedBox(width: 12),
            if (!viewOnly)
              Expanded(
                child: current == TransferTab.send
                    ? PrimaryButton(label: "Send", onPressed: () {})
                    : SecondaryButton(
                        label: "Send",
                        onPressed: () =>
                            Navigator.of(context).pushReplacementNamed(
                              SendView.routeName,
                              arguments: (walletId: walletId, coin: coin),
                            ),
                      ),
              ),
            const SizedBox(width: 12),
            SecondaryButton(
              width: 56,
              icon: Icon(
                Icons.more_horiz,
                size: 22,
                color: colors.buttonTextSecondary,
              ),
              onPressed: () => _showExtrasSheet(context, ref),
            ),
          ],
        ),
      ),
    );
  }
}
