/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';

import '../pages/receive_view/receive_view.dart';
import '../pages/send_view/send_view.dart';
import '../wallets/crypto_currency/crypto_currency.dart';
import 'wallet_navigation_bar/components/icons/receive_nav_icon.dart';
import 'wallet_navigation_bar/components/icons/send_nav_icon.dart';
import 'wallet_navigation_bar/components/wallet_navigation_bar_item.dart';
import 'wallet_navigation_bar/wallet_navigation_bar.dart';

/// Which Receive/Send flow the page is currently showing.
enum TransferTab { receive, send }

/// The wallet dock, on the Receive/Send pages. It is the *same* floating
/// WalletNavigationBar used on the wallet view — so navigation reads as one
/// language everywhere — with Receive/Send jumping between the two flows via
/// pushReplacement (the back stack stays clean; both still pop to the wallet
/// view). The action for the page you are already on is disabled.
class ReceiveSendSwitchDock extends StatelessWidget {
  const ReceiveSendSwitchDock({
    super.key,
    required this.current,
    required this.walletId,
    required this.coin,
  });

  final TransferTab current;
  final String walletId;
  final CryptoCurrency coin;

  @override
  Widget build(BuildContext context) {
    return WalletNavigationBar(
      floating: true,
      items: [
        WalletNavigationBarItemData(
          label: "Receive",
          icon: const ReceiveNavIcon(),
          onTap: current == TransferTab.receive
              ? null
              : () => Navigator.of(context).pushReplacementNamed(
                  ReceiveView.routeName,
                  arguments: walletId,
                ),
        ),
        WalletNavigationBarItemData(
          label: "Send",
          icon: const SendNavIcon(),
          onTap: current == TransferTab.send
              ? null
              : () => Navigator.of(context).pushReplacementNamed(
                  SendView.routeName,
                  arguments: (walletId: walletId, coin: coin),
                ),
        ),
      ],
      moreItems: const [],
    );
  }
}
