/*
 * This file is part of Stack Wallet.
 *
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/svg.dart';
import 'package:tuple/tuple.dart';

import '../pages/coin_control/coin_control_view.dart';
import '../pages/receive_view/receive_view.dart';
import '../pages/send_view/send_view.dart';
import '../pages/wallet_view/transaction_views/tx_v2/all_transactions_v2_view.dart';
import '../providers/providers.dart';
import '../themes/stack_colors.dart';
import '../utilities/assets.dart';
import '../wallets/crypto_currency/crypto_currency.dart';
import 'wallet_navigation_bar/components/icons/coin_control_nav_icon.dart';
import 'wallet_navigation_bar/components/icons/receive_nav_icon.dart';
import 'wallet_navigation_bar/components/icons/send_nav_icon.dart';
import 'wallet_navigation_bar/components/wallet_navigation_bar_item.dart';
import 'wallet_navigation_bar/wallet_navigation_bar.dart';

/// Which Receive/Send flow the page is currently showing.
enum TransferTab { receive, send }

/// The wallet dock, on the Receive/Send pages. It is the *same* floating
/// WalletNavigationBar used on the wallet view — Receive / Send / More — so
/// navigation reads as one language everywhere. Receive/Send jump between the
/// two flows via pushReplacement (the back stack stays clean; both still pop to
/// the wallet view), the action for the current page is disabled, and More
/// opens an overflow sheet (All transactions, plus Coin control when enabled).
class ReceiveSendSwitchDock extends ConsumerWidget {
  const ReceiveSendSwitchDock({
    super.key,
    required this.current,
    required this.walletId,
    required this.coin,
  });

  final TransferTab current;
  final String walletId;
  final CryptoCurrency coin;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final colors = Theme.of(context).extension<StackColors>()!;

    return WalletNavigationBar(
      floating: true,
      items: [
        WalletNavigationBarItemData(
          label: "Receive",
          icon: const ReceiveNavIcon(),
          onTap: current == TransferTab.receive
              ? null
              : () => Navigator.of(context).pushReplacementNamed(
                  ReceiveView.routeName,
                  arguments: walletId,
                ),
        ),
        WalletNavigationBarItemData(
          label: "Send",
          icon: const SendNavIcon(),
          onTap: current == TransferTab.send
              ? null
              : () => Navigator.of(context).pushReplacementNamed(
                  SendView.routeName,
                  arguments: (walletId: walletId, coin: coin),
                ),
        ),
      ],
      moreItems: <WalletNavigationBarItemData>[
        WalletNavigationBarItemData(
          label: "All transactions",
          icon: SvgPicture.asset(
            Assets.svg.list,
            width: 20,
            height: 20,
            color: colors.bottomNavIconIcon,
          ),
          onTap: () => Navigator.of(context).pushNamed(
            AllTransactionsV2View.routeName,
            arguments: walletId,
          ),
        ),
        if (ref.watch(
          prefsChangeNotifierProvider.select((value) => value.enableCoinControl),
        ))
          WalletNavigationBarItemData(
            label: "Coin control",
            icon: const CoinControlNavIcon(),
            onTap: () => Navigator.of(context).pushNamed(
              CoinControlView.routeName,
              arguments: Tuple2(walletId, CoinControlViewType.manage),
            ),
          ),
      ],
    );
  }
}
