/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import '../themes/stack_colors.dart';
import '../utilities/constants.dart';
import 'rounded_container.dart';

class RoundedWhiteContainer extends StatelessWidget {
  const RoundedWhiteContainer({
    super.key,
    this.child,
    this.padding = const EdgeInsets.all(12),
    this.radiusMultiplier,
    this.width,
    this.height,
    this.borderColor,
    this.hoverColor,
    this.boxShadow,
    this.onPressed,
  });

  final Widget? child;
  final EdgeInsets padding;
  final double? radiusMultiplier;
  final double? width;
  final double? height;
  final Color? borderColor;
  final Color? hoverColor;
  final List<BoxShadow>? boxShadow;
  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).extension<StackColors>()!;
    return RoundedContainer(
      color: colors.popupBG,
      padding: padding,
      // The redesign's card is 16px with a hairline, not a borderless 12px
      // box. Applied here rather than at ~209 call sites; a caller that passes
      // its own multiplier or border still wins.
      radiusMultiplier:
          radiusMultiplier ??
          (Constants.size.cardBorderRadius / Constants.size.circularBorderRadius),
      width: width,
      height: height,
      // Derived, not the spec's literal #E4E4E7: a fixed light grey would be
      // invisible on the dark themes. textSubtitle1 tracks each theme's ink,
      // matching the hairline the transaction cards already use.
      borderColor: borderColor ?? colors.textSubtitle1.withOpacity(0.1),
      boxShadow: boxShadow,
      hoverColor: hoverColor,
      onPressed: onPressed,
      child: child,
    );
  }
}
