/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/isar/stack_theme.dart';
import '../wallets/crypto_currency/crypto_currency.dart';
import 'theme_providers.dart';
import 'theme_service.dart';

/// Coin asset from the bundled default themes, for themes that predate a coin.
///
/// The five external themes on themes.bitfinitechain.org ship upstream's coin
/// list, so they have no entry for Bellscoin (and pre-v2.0.0, none for
/// Pepecoin). Their lookups then showed a WRONG icon, so applying any external
/// theme silently re-branded our own coins. Asset paths are theme-scoped
/// ("<themeId>/assets/…") and every installed theme lives under the same
/// root, so an entry read from the always-installed bundled light/dark theme
/// resolves fine while any other theme is active.
///
/// NOTE the subtlety that made the first version of this dead code:
/// parseCoinAssetsString fills EVERY supported coin, substituting the theme's
/// coin_placeholder when the theme's json lacks the key — so a plain
/// null-check on the map never fires. "Missing" means placeholder-valued,
/// which is what [realCoinAsset] tests.
String? realCoinAsset(
  Map<String, String>? map,
  String? placeholder,
  String key,
) {
  final value = map?[key];
  if (value == null || value == placeholder) return null;
  return value;
}

String? bundledThemeCoinAsset(
  Ref ref,
  CryptoCurrency coin,
  Map<String, String>? Function(IThemeAssets assets) select,
) {
  for (final themeId in ["light", "dark"]) {
    final theme = ref.watch(pThemeService).getTheme(themeId: themeId);
    final assets = theme?.assets;
    if (assets == null) continue;
    final value = realCoinAsset(
      select(assets),
      coinPlaceholderOf(assets),
      coin.mainNetId,
    );
    if (value != null) return value;
  }
  return null;
}

String? coinPlaceholderOf(IThemeAssets a) => a is ThemeAssetsV3
    ? a.coinPlaceholder
    : a is ThemeAssetsV2
        ? a.coinPlaceholder
        : null;

Map<String, String>? coinIconsOf(IThemeAssets a) => a is ThemeAssetsV3
    ? a.coinIcons
    : a is ThemeAssetsV2
        ? a.coinIcons
        : null;

Map<String, String>? coinImagesOf(IThemeAssets a) => a is ThemeAssetsV3
    ? a.coinImages
    : a is ThemeAssetsV2
        ? a.coinImages
        : null;

Map<String, String>? coinSecondaryImagesOf(IThemeAssets a) =>
    a is ThemeAssetsV3
        ? a.coinSecondaryImages
        : a is ThemeAssetsV2
            ? a.coinSecondaryImages
            : null;

final coinIconProvider = Provider.family<String, CryptoCurrency>((ref, coin) {
  final assets = ref.watch(themeAssetsProvider);

  if (assets is ThemeAssets) {
    switch (coin.runtimeType) {
      case const (Bitcoin):
        return assets.bitcoin;
      case const (Litecoin):
        return assets.litecoin;
      case const (Bitcoincash):
        return assets.bitcoincash;
      // TODO(bfx): ship a dedicated BitFinite icon per theme; BCH icon as placeholder.
      case const (Bitfinite):
        return assets.bitcoincash;
      case const (Dogecoin):
        return assets.dogecoin;
      // V1 themes only. Their assets are named Dart fields, so a coin added
      // after the model was written cannot have its own entry — Dogecoin's is
      // the closest stand-in, Pepecoin being a Dogecoin fork. V2/V3 themes take
      // the branch below and read a real pepecoin icon from coins.icons.
      case const (Pepecoin):
        return assets.dogecoin;
      // Same V1-theme constraint as Pepecoin above; Bellscoin is a
      // Doge-family scrypt coin, so Dogecoin's icon is the stand-in.
      case const (Bellscoin):
        return assets.dogecoin;
      case const (Epiccash):
        return assets.epicCash;
      case const (Firo):
        return assets.firo;
      case const (Monero):
        return assets.monero;
      case const (Wownero):
        return assets.wownero;
      case const (Namecoin):
        return assets.namecoin;
      case const (Particl):
        return assets.particl;
      case const (Ethereum):
        return assets.ethereum;
      default:
        return assets.stackIcon;
    }
  } else if (assets is ThemeAssetsV2) {
    // A coin the active theme predates keeps its own icon from the bundled
    // theme; the theme's placeholder is the fallback after that, and only
    // then bitcoincash (kept for themes with no placeholder at all).
    return realCoinAsset(
          assets.coinIcons,
          assets.coinPlaceholder,
          coin.mainNetId,
        ) ??
        bundledThemeCoinAsset(ref, coin, coinIconsOf) ??
        (assets).coinIcons[coin.mainNetId] ??
        (assets).coinIcons["bitcoincash"] ??
        (assets).coinIcons.values.first;
  } else {
    final a = assets as ThemeAssetsV3;
    return realCoinAsset(a.coinIcons, a.coinPlaceholder, coin.mainNetId) ??
        bundledThemeCoinAsset(ref, coin, coinIconsOf) ??
        a.coinIcons[coin.mainNetId] ??
        a.coinIcons["bitcoincash"] ??
        a.coinIcons.values.first;
  }
});
