/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'dart:typed_data';

import 'package:decimal/decimal.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/flutter_svg.dart';

import '../../../notifications/show_flush_bar.dart';
import '../../../providers/providers.dart';
import '../../../providers/wallet/public_private_balance_state_provider.dart';
import '../../../providers/wallet/wallet_balance_toggle_state_provider.dart';
import '../../../services/event_bus/events/global/wallet_sync_status_changed_event.dart';
import '../../../themes/stack_colors.dart';
import '../../../utilities/amount/amount.dart';
import '../../../utilities/amount/amount_formatter.dart';
import '../../../utilities/assets.dart';
import '../../../utilities/enums/wallet_balance_toggle_state.dart';
import '../../../utilities/extensions/extensions.dart';
import '../../../utilities/text_styles.dart';
import '../../../wallets/crypto_currency/coins/banano.dart';
import '../../../wallets/crypto_currency/coins/firo.dart';
import '../../../wallets/isar/providers/wallet_info_provider.dart';
import '../../../wallets/wallet/impl/banano_wallet.dart';
import '../../../widgets/conditional_parent.dart';
import '../../../widgets/coin_card.dart';
import 'wallet_balance_toggle_sheet.dart';
import 'wallet_sync_chip.dart';

class WalletSummaryInfo extends ConsumerWidget {
  const WalletSummaryInfo({
    super.key,
    required this.walletId,
    required this.initialSyncStatus,
  });

  final String walletId;
  final WalletSyncStatus initialSyncStatus;

  void showSheet(BuildContext context) {
    showModalBottomSheet<dynamic>(
      backgroundColor: Colors.transparent,
      context: context,
      useSafeArea: true,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => WalletBalanceToggleSheet(walletId: walletId),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    debugPrint("BUILD: $runtimeType");

    final coin = ref.watch(pWalletCoin(walletId));
    final balance = ref.watch(pWalletBalance(walletId));

    final locale = ref.watch(
      localeServiceChangeNotifierProvider.select((value) => value.locale),
    );

    final baseCurrency = ref.watch(
      prefsChangeNotifierProvider.select((value) => value.currency),
    );

    ({double change24h, Decimal value})? price;
    if (ref.watch(
      prefsChangeNotifierProvider.select((value) => value.externalCalls),
    )) {
      price = ref.watch(
        priceAnd24hChangeNotifierProvider.select(
          (value) => value.getPrice(coin),
        ),
      );
    }

    final _showAvailable =
        ref.watch(walletBalanceToggleStateProvider) ==
        WalletBalanceToggleState.available;

    final Amount balanceToShow;
    final String title;

    final bool toggleBalance;

    if (coin is Firo || ref.watch(pWalletInfo(walletId)).isMwebEnabled) {
      toggleBalance = false;
      final type = ref.watch(publicPrivateBalanceStateProvider.state).state;
      title =
          "${_showAvailable ? "Available" : "Full"} ${type.name.capitalize()} balance";
      switch (type) {
        case BalanceType.private:
          final balance =
              coin is Firo
                  ? ref.watch(pWalletBalanceTertiary(walletId))
                  : ref.watch(pWalletBalanceSecondary(walletId));
          balanceToShow = _showAvailable ? balance.spendable : balance.total;
          break;

        case BalanceType.public:
          final balance = ref.watch(pWalletBalance(walletId));
          balanceToShow = _showAvailable ? balance.spendable : balance.total;
          break;
      }
    } else {
      toggleBalance = true;
      balanceToShow = _showAvailable ? balance.spendable : balance.total;
      title = _showAvailable ? "Available balance" : "Full balance";
    }

    List<int>? imageBytes;

    if (coin is Banano) {
      imageBytes =
          (ref.watch(pWallets).getWallet(walletId) as BananoWallet)
              .getMonkeyImageBytes();
    }

    // Hero balance: split the formatted amount into a full-weight part and
    // de-emphasized trailing "dust" decimals (locale-safe: the decimal
    // separator is whatever [.,] appears last in the numeric string).
    final formatter = ref.watch(pAmountFormatter(coin));
    final String fullStr = formatter.format(balanceToShow);
    final String numStr = formatter.format(balanceToShow, withUnitName: false);
    final String unitStr =
        fullStr.startsWith(numStr)
            ? fullStr.substring(numStr.length).trim()
            : coin.ticker;
    String mainPart = numStr;
    String dustPart = "";
    final sepIdx = numStr.lastIndexOf(RegExp(r"[.,]"));
    if (sepIdx > 0) {
      final decimals = numStr.substring(sepIdx + 1);
      if (decimals.length > 2) {
        mainPart = numStr.substring(0, sepIdx + 3);
        dustPart = decimals.substring(2);
      }
    }

    // Balance-first block sits on the page background now (no gradient card),
    // so the text is themed ink rather than on-card white.
    final favText = Theme.of(context).extension<StackColors>()!.textDark;
    final receivingAddress = ref.watch(pWalletReceivingAddress(walletId));
    final heroStyle = STextStyles.pageTitleH1(context).copyWith(
      fontSize: 42,
      fontWeight: FontWeight.w800,
      height: 1.05,
      letterSpacing: -1.2,
      color: favText,
      fontFeatures: const [FontFeature.tabularFigures()],
    );

    return ConditionalParent(
      condition: imageBytes != null,
      builder:
          (child) => Stack(
            children: [
              Positioned.fill(
                left: 150.0,
                child: SvgPicture.memory(Uint8List.fromList(imageBytes!)),
              ),
              child,
            ],
          ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: GestureDetector(
                  onTap: () {
                    if (toggleBalance) {
                      if (ref.read(walletBalanceToggleStateProvider) ==
                          WalletBalanceToggleState.available) {
                        ref
                            .read(walletBalanceToggleStateProvider.notifier)
                            .state = WalletBalanceToggleState.full;
                      } else {
                        ref
                            .read(walletBalanceToggleStateProvider.notifier)
                            .state = WalletBalanceToggleState.available;
                      }
                    } else {
                      showSheet(context);
                    }
                  },
                  child: Row(
                    children: [
                      Flexible(
                        child: Text(
                          title.toUpperCase(),
                          overflow: TextOverflow.ellipsis,
                          style: STextStyles.subtitle500(context).copyWith(
                            fontSize: 11,
                            fontWeight: FontWeight.w600,
                            letterSpacing: 1.6,
                            color: favText.withOpacity(0.8),
                          ),
                        ),
                      ),
                      const SizedBox(width: 5),
                      SvgPicture.asset(
                        Assets.svg.chevronDown,
                        color: favText.withOpacity(0.8),
                        width: 8,
                        height: 4,
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(width: 8),
              WalletSyncChip(
                walletId: walletId,
                initialSyncStatus: initialSyncStatus,
              ),
            ],
          ),
          const SizedBox(height: 18),
          if (ref.watch(pWalletInfo(walletId)).isViewOnly)
            FittedBox(
              fit: BoxFit.scaleDown,
              child: SelectableText(
                "(View only)",
                style: STextStyles.pageTitleH1(
                  context,
                ).copyWith(fontSize: 18, color: favText.withOpacity(0.7)),
              ),
            ),
          FittedBox(
            fit: BoxFit.scaleDown,
            child: SelectableText.rich(
              TextSpan(
                children: [
                  TextSpan(text: mainPart, style: heroStyle),
                  if (dustPart.isNotEmpty)
                    TextSpan(
                      text: dustPart,
                      style: heroStyle.copyWith(
                        fontSize: 22,
                        fontWeight: FontWeight.w700,
                        color: favText.withOpacity(0.4),
                      ),
                    ),
                  TextSpan(
                    text: " $unitStr",
                    style: heroStyle.copyWith(
                      fontSize: 18,
                      fontWeight: FontWeight.w700,
                      color: favText.withOpacity(0.85),
                    ),
                  ),
                ],
              ),
            ),
          ),
          if (receivingAddress.isNotEmpty)
            Padding(
              padding: const EdgeInsets.only(top: 14),
              child: GestureDetector(
                onTap: () {
                  unawaited(HapticFeedback.lightImpact());
                  Clipboard.setData(ClipboardData(text: receivingAddress));
                  unawaited(
                    showFloatingFlushBar(
                      type: FlushBarType.info,
                      message: "Address copied to clipboard",
                      iconAsset: Assets.svg.copy,
                      context: context,
                    ),
                  );
                },
                child: Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 8,
                  ),
                  decoration: BoxDecoration(
                    color: Theme.of(
                      context,
                    ).extension<StackColors>()!.textFieldDefaultBG,
                    borderRadius: BorderRadius.circular(10),
                    border: Border.all(
                      color: favText.withOpacity(0.08),
                      width: 1,
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        receivingAddress.length > 22
                            ? "${receivingAddress.substring(0, 12)}…"
                                "${receivingAddress.substring(receivingAddress.length - 6)}"
                            : receivingAddress,
                        style: STextStyles.subtitle500(context).copyWith(
                          fontSize: 12.5,
                          color: favText.withOpacity(0.7),
                          fontFeatures: const [FontFeature.tabularFigures()],
                        ),
                      ),
                      const SizedBox(width: 8),
                      SvgPicture.asset(
                        Assets.svg.copy,
                        width: 13,
                        height: 13,
                        color: favText.withOpacity(0.45),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          // Fiat is noise while no real price feed exists (provider returns 0
          // for unlisted coins) — show it only when there's an actual price.
          if (price != null && price.value > Decimal.zero)
            Padding(
              padding: const EdgeInsets.only(top: 2),
              child: Text(
                "${(price.value * balanceToShow.decimal).toAmount(fractionDigits: 2).fiatString(locale: locale)} $baseCurrency",
                style: STextStyles.subtitle500(
                  context,
                ).copyWith(color: favText),
              ),
            ),
        ],
      ),
    );
  }
}
