/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';
import 'dart:typed_data';

import 'package:decimal/decimal.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/flutter_svg.dart';

import '../../settings_views/global_settings_view/advanced_views/manage_coin_units/edit_coin_units_view.dart';
import '../../../notifications/show_flush_bar.dart';
import '../../../providers/providers.dart';
import '../../../providers/wallet/public_private_balance_state_provider.dart';
import '../../../providers/wallet/wallet_balance_toggle_state_provider.dart';
import '../../../services/event_bus/events/global/wallet_sync_status_changed_event.dart';
import '../../../themes/stack_colors.dart';
import '../../../themes/theme_providers.dart';
import '../../../utilities/hero_ink.dart';
import '../../../utilities/amount/amount.dart';
import '../../../utilities/amount/amount_formatter.dart';
import '../../../utilities/assets.dart';
import '../../../utilities/enums/wallet_balance_toggle_state.dart';
import '../../../utilities/extensions/extensions.dart';
import '../../../utilities/text_styles.dart';
import '../../../wallets/crypto_currency/coins/banano.dart';
import '../../../wallets/crypto_currency/coins/firo.dart';
import '../../../wallets/isar/providers/wallet_info_provider.dart';
import '../../../wallets/wallet/impl/banano_wallet.dart';
import '../../../widgets/price_sparkline.dart';
import '../../../widgets/conditional_parent.dart';
import '../../../widgets/coin_card.dart';
import 'wallet_balance_toggle_sheet.dart';
import 'wallet_sync_chip.dart';

class WalletSummaryInfo extends ConsumerWidget {
  const WalletSummaryInfo({
    super.key,
    required this.walletId,
    required this.initialSyncStatus,
  });

  final String walletId;
  final WalletSyncStatus initialSyncStatus;

  void showSheet(BuildContext context) {
    showModalBottomSheet<dynamic>(
      backgroundColor: Colors.transparent,
      context: context,
      useSafeArea: true,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => WalletBalanceToggleSheet(walletId: walletId),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    debugPrint("BUILD: $runtimeType");

    final coin = ref.watch(pWalletCoin(walletId));
    final balance = ref.watch(pWalletBalance(walletId));

    final locale = ref.watch(
      localeServiceChangeNotifierProvider.select((value) => value.locale),
    );

    final baseCurrency = ref.watch(
      prefsChangeNotifierProvider.select((value) => value.currency),
    );

    // Watched via select so toggling it rebuilds only this block.
    final privacyMode = ref.watch(
      prefsChangeNotifierProvider.select((value) => value.privacyMode),
    );

    ({double change24h, Decimal value})? price;
    if (ref.watch(
      prefsChangeNotifierProvider.select((value) => value.externalCalls),
    )) {
      price = ref.watch(
        priceAnd24hChangeNotifierProvider.select(
          (value) => value.getPrice(coin),
        ),
      );
    }

    final _showAvailable =
        ref.watch(walletBalanceToggleStateProvider) ==
        WalletBalanceToggleState.available;

    final Amount balanceToShow;
    final String title;

    final bool toggleBalance;

    if (coin is Firo || ref.watch(pWalletInfo(walletId)).isMwebEnabled) {
      toggleBalance = false;
      final type = ref.watch(publicPrivateBalanceStateProvider.state).state;
      title =
          "${_showAvailable ? "Available" : "Full"} ${type.name.capitalize()} balance";
      switch (type) {
        case BalanceType.private:
          final balance =
              coin is Firo
                  ? ref.watch(pWalletBalanceTertiary(walletId))
                  : ref.watch(pWalletBalanceSecondary(walletId));
          balanceToShow = _showAvailable ? balance.spendable : balance.total;
          break;

        case BalanceType.public:
          final balance = ref.watch(pWalletBalance(walletId));
          balanceToShow = _showAvailable ? balance.spendable : balance.total;
          break;
      }
    } else {
      toggleBalance = true;
      balanceToShow = _showAvailable ? balance.spendable : balance.total;
      title = _showAvailable ? "Available balance" : "Full balance";
    }

    List<int>? imageBytes;

    if (coin is Banano) {
      imageBytes =
          (ref.watch(pWallets).getWallet(walletId) as BananoWallet)
              .getMonkeyImageBytes();
    }

    // Hero balance: split the formatted amount into a full-weight part and
    // de-emphasized trailing "dust" decimals (locale-safe: the decimal
    // separator is whatever [.,] appears last in the numeric string).
    final formatter = ref.watch(pAmountFormatter(coin));
    final String fullStr = formatter.format(balanceToShow);
    final String numStr = formatter.format(balanceToShow, withUnitName: false);
    final String unitStr =
        fullStr.startsWith(numStr)
            ? fullStr.substring(numStr.length).trim()
            : coin.ticker;
    String mainPart = numStr;
    String dustPart = "";
    final sepIdx = numStr.lastIndexOf(RegExp(r"[.,]"));
    if (sepIdx > 0) {
      final decimals = numStr.substring(sepIdx + 1);
      if (decimals.length > 2) {
        mainPart = numStr.substring(0, sepIdx + 3);
        dustPart = decimals.substring(2);
      }
    }

    // Privacy mode: replace the digits entirely rather than blurring or
    // shrinking them. A fixed-width mask also means the hero does not change
    // size when toggled, so it cannot leak the magnitude of the balance
    // through its own layout.
    if (privacyMode) {
      mainPart = "••••••";
      dustPart = "";
    }

    // This block sits on the solid hero, not on the page background, so it
    // needs on-hero ink rather than themed ink. Themed ink would be dark in
    // the light theme, sitting illegibly on a saturated fill — the same trap
    // coin_card.dart documents for BitFinite's colour.
    //
    // It does NOT follow the theme's brightness, but it cannot be hardcoded
    // white either: the hero is the theme's own colour, which is a light
    // orange in some themes where white measures 3.00:1. heroInk derives it
    // from the fill. Every label here is built from favText, so this one value
    // carries the whole block.
    final favText = heroInk(ref.watch(pCoinColor(coin)));
    final receivingAddress = ref.watch(pWalletReceivingAddress(walletId));
    // Spec: 52px / 700 / letter-spacing -0.02em, tabular. -0.02em at 52px is
    // -1.04, so the previous -1.2 was slightly tighter than intended; w800 was
    // also heavier than the design, which relies on size rather than weight to
    // carry the balance.
    // 36, down again from 44 (which was down from the spec's 52): the user
    // asked for a compact hero that stops crowding the transaction list. 36
    // still outranks everything under it by a wide margin — the fiat line is
    // 13 — and hierarchy comes from the gap, not the absolute size. The
    // -0.02em tracking follows the size: -0.02 x 36.
    final heroStyle = STextStyles.pageTitleH1(context).copyWith(
      fontSize: 36,
      fontWeight: FontWeight.w700,
      height: 1.05,
      letterSpacing: -0.72,
      color: favText,
      fontFeatures: const [FontFeature.tabularFigures()],
    );

    return ConditionalParent(
      condition: imageBytes != null,
      builder:
          (child) => Stack(
            children: [
              Positioned.fill(
                left: 150.0,
                child: SvgPicture.memory(Uint8List.fromList(imageBytes!)),
              ),
              child,
            ],
          ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Seven days of price, from the series the price API already returns.
          // Gated on the same price != null as the fiat line above, and
          // getSparkline gates itself again — a coin with no market gets no
          // chart rather than a flat line at zero, which would be a claim we
          // cannot support. Hidden in privacy mode for the same reason the fiat
          // figure is: the shape still tells you how the holding moved.
          if (price != null && price.value > Decimal.zero && !privacyMode)
            Builder(
              builder: (context) {
                final series = ref
                    .read(priceAnd24hChangeNotifierProvider)
                    .getSparkline(coin);
                if (series == null) return const SizedBox.shrink();
                return Padding(
                  padding: const EdgeInsets.only(bottom: 10),
                  child: Container(
                        padding: const EdgeInsets.fromLTRB(8, 6, 8, 4),
                        decoration: BoxDecoration(
                          // A faint well so the line has an edge to sit on;
                          // floating on the hero fill it read as a stray mark.
                          // Same white the text uses, far quieter, so it follows
                          // whatever coin colour the hero takes.
                          color: favText.withOpacity(0.08),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: PriceSparkline(
                          series: series,
                          color: favText.withOpacity(0.9),
                          height: 36,
                          // The same formatter as the fiat figure above, so a
                          // price read off the chart and the value printed
                          // over it cannot disagree about how to write a
                          // number smaller than a cent.
                          format: (v) =>
                              "${Decimal.parse(v.toString()).toAmount(fractionDigits: 8).fiatString(locale: locale)} $baseCurrency",
                        ),
                      ),
                );
              },
            ),
          Row(
            children: [
              Expanded(
                child: GestureDetector(
                  onTap: () {
                    if (toggleBalance) {
                      if (ref.read(walletBalanceToggleStateProvider) ==
                          WalletBalanceToggleState.available) {
                        ref
                            .read(walletBalanceToggleStateProvider.notifier)
                            .state = WalletBalanceToggleState.full;
                      } else {
                        ref
                            .read(walletBalanceToggleStateProvider.notifier)
                            .state = WalletBalanceToggleState.available;
                      }
                    } else {
                      showSheet(context);
                    }
                  },
                  child: Row(
                    children: [
                      Flexible(
                        child: Text(
                          title.toUpperCase(),
                          overflow: TextOverflow.ellipsis,
                          // Spec: 12px / 600 / 0.1em tracking (= 1.2 at 12px).
                          //
                          // Opacity deliberately stays at 0.80 rather than the
                          // spec's 0.72: measured on blue-600, 0.72 gives
                          // 4.19:1 and 0.76 gives 4.49:1 — both under the 4.5:1
                          // AA floor for text this size. 0.80 is the first
                          // passing step at 4.84:1. The design's intent is a
                          // de-emphasised label, and 0.80 still reads as one;
                          // shipping 0.72 would just be an unreadable one.
                          style: STextStyles.subtitle500(context).copyWith(
                            fontSize: 12,
                            fontWeight: FontWeight.w600,
                            letterSpacing: 1.2,
                            color: favText.withOpacity(0.8),
                          ),
                        ),
                      ),
                      const SizedBox(width: 5),
                      SvgPicture.asset(
                        Assets.svg.chevronDown,
                        color: favText.withOpacity(0.8),
                        width: 8,
                        height: 4,
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(width: 8),
              // Privacy toggle. Sits beside the label it governs rather than in
              // a menu: hiding your balance is something you do *now*, because
              // of who is next to you, so it has to be one tap from the number
              // it hides.
              GestureDetector(
                behavior: HitTestBehavior.opaque,
                onTap: () {
                  final prefs = ref.read(prefsChangeNotifierProvider);
                  prefs.privacyMode = !prefs.privacyMode;
                },
                child: Padding(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 6,
                    vertical: 4,
                  ),
                  child: SvgPicture.asset(
                    privacyMode ? Assets.svg.eyeSlash : Assets.svg.eye,
                    // Same ink as the label; on the hero everything derives
                    // from the hero, never from the page theme.
                    color: favText.withOpacity(0.8),
                    width: 18,
                    height: 18,
                  ),
                ),
              ),
              const SizedBox(width: 4),
              WalletSyncChip(
                walletId: walletId,
                initialSyncStatus: initialSyncStatus,
              ),
            ],
          ),
          const SizedBox(height: 10),
          if (ref.watch(pWalletInfo(walletId)).isViewOnly)
            FittedBox(
              fit: BoxFit.scaleDown,
              child: SelectableText(
                "(View only)",
                style: STextStyles.pageTitleH1(
                  context,
                // w600/18px is not "large text" by WCAG (that needs w700 at
                // >=18.66px), so this owes the full 4.5:1. 0.7 measured
                // 4.03:1; 0.8 gives 4.84:1 and matches the other hero labels.
                ).copyWith(fontSize: 18, color: favText.withOpacity(0.8)),
              ),
            ),
          GestureDetector(
            behavior: HitTestBehavior.opaque,
            // Tap the balance to change how many decimals are shown, per coin
            // (Settings > Advanced > Manage coin units). Nothing is hardcoded.
            onTap: () => Navigator.of(context).pushNamed(
              EditCoinUnitsView.routeName,
              arguments: coin,
            ),
            child: FittedBox(
              fit: BoxFit.scaleDown,
              child: Text.rich(
                TextSpan(
                  children: [
                    TextSpan(text: mainPart, style: heroStyle),
                    if (dustPart.isNotEmpty)
                      TextSpan(
                        text: dustPart,
                        style: heroStyle.copyWith(
                          fontSize: 18,
                          fontWeight: FontWeight.w700,
                          // 0.4 measured 2.21:1 on blue-600 — under even the
                          // 3:1 large-text floor, and these are real satoshi
                          // digits of the balance, not decoration. 0.62 gives
                          // 3.46:1 and still reads as secondary against the
                          // 52px full-opacity main part.
                          color: favText.withOpacity(0.62),
                        ),
                      ),
                    TextSpan(
                      text: " $unitStr",
                      style: heroStyle.copyWith(
                        fontSize: 16,
                        fontWeight: FontWeight.w700,
                        color: favText.withOpacity(0.85),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          // Fiat sits directly under the balance it converts, above the address:
          // the two are the same quantity in two units, and putting an unrelated
          // chip between them made the second read as a third number. Quieter
          // than the balance — it restates it rather than adding a fact.
          //
          // "≈" because it genuinely is approximate: a cached market price
          // against a balance, not an amount anyone will receive.
          if (price != null && price.value > Decimal.zero)
            Padding(
              padding: const EdgeInsets.only(top: 4, bottom: 2),
              child: Text(
                // Masked too: hiding the BFX figure while showing its fiat
                // value would defeat the point entirely.
                privacyMode
                    ? "•••• $baseCurrency"
                    : "≈ ${(price.value * balanceToShow.decimal).toAmount(fractionDigits: 8).fiatString(locale: locale)} $baseCurrency",
                style: STextStyles.subtitle500(
                  context,
                ).copyWith(color: favText.withOpacity(0.78), fontSize: 13),
              ),
            ),
          if (receivingAddress.isNotEmpty)
            Padding(
              padding: const EdgeInsets.only(top: 10),
              child: GestureDetector(
                onTap: () {
                  unawaited(HapticFeedback.lightImpact());
                  Clipboard.setData(ClipboardData(text: receivingAddress));
                  unawaited(
                    showFloatingFlushBar(
                      type: FlushBarType.info,
                      message: "Address copied to clipboard",
                      iconAsset: Assets.svg.copy,
                      context: context,
                    ),
                  );
                },
                child: Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 6,
                  ),
                  decoration: BoxDecoration(
                    // Derived from the hero ink, NOT from the page theme.
                    // textFieldDefaultBG is a *page* surface colour: near-white
                    // in the light and forest themes, which put white text on
                    // white and made the address unreadable in two themes out
                    // of three. A translucent white scrim works on any hero
                    // colour — today's blue, forest's teal, whatever a future
                    // coin colour brings — because it is the same white the
                    // text already uses, just quieter.
                    // Redesign spec values: rgba(255,255,255,0.12) fill,
                    // 0.22 border, 12px radius. These are tuned for blue-600
                    // #0644F1 — on the old #2F6BFF they would fail AA, which
                    // is why the coin colour moved to blue-600 alongside this.
                    color: favText.withOpacity(0.12),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: favText.withOpacity(0.22),
                      width: 1,
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        receivingAddress.length > 22
                            ? "${receivingAddress.substring(0, 12)}…"
                                "${receivingAddress.substring(receivingAddress.length - 6)}"
                            : receivingAddress,
                        style: STextStyles.subtitle500(context).copyWith(
                          // Spec: 13px monospace at 0.92. On blue-600 that is
                          // 5.94:1 — comfortably AA. The same 0.92 on the old
                          // #2F6BFF was 4.05:1 and failed.
                          fontSize: 13,
                          color: favText.withOpacity(0.92),
                          fontFeatures: const [FontFeature.tabularFigures()],
                        ),
                      ),
                      const SizedBox(width: 8),
                      SvgPicture.asset(
                        Assets.svg.copy,
                        width: 14,
                        height: 14,
                        // The only affordance signalling the chip is tappable,
                        // so it has to be findable rather than decorative.
                        color: favText.withOpacity(0.8),
                      ),
                    ],
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}
